apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\drago\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: portainer
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\drago\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/proiect-default: "true"
        io.kompose.service: portainer
    spec:
      containers:
        - image: portainer/portainer-ce:latest
          name: portainer
          ports:
            - containerPort: 9443
              hostPort: 9443
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /var/run/docker.sock
              name: portainer-claim1
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: portainer-claim1
          persistentVolumeClaim:
            claimName: portainer-claim1
status: {}
