apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\drago\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: portainer
  name: portainer
spec:
  ports:
    - name: "9443"
      port: 9443
      targetPort: 9443
  selector:
    io.kompose.service: portainer
status:
  loadBalancer: {}
